services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: always
    expose:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - DB_NAME: ${DB_NAME}
      - DB_USER: ${DB_USER}
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception

  wordpress:
    build: 
      context: ./requirements/wordpress
    container_name: wordpress
    restart: always
    expose:
      - "${WP_PORT}"
    volumes:
      - wp-data:/var/www/wordpress
    depends_on:
      - mariadb
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
    secrets:
      - db_password
    networks:
      - inception

  nginx:
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports: 
      - "${ENTRY_PORT}:443"
    volumes:
      - wp-data:/var/www/wordpress:ro
    depends_on:
      - wordpress
    networks:
      - inception

volumes:
  mysql:
  wp-data: 

networks:
    inception:
      driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt