services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    expose:
      - "3306"
    volumes:
      - "mysql:/var/lib/mysql"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
  wordpress:
    build: 
      context: ./requirements/wordpress
    container_name: wordpress
    restart: always
    expose:
      - "9000"
    volumes:
      - wp-data:/var/www/wordpress
    networks:
      - inception
  nginx:
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports: 
      - "8080:80"
    volumes:
      - wp-data:/var/www/wordpress:ro
    depends_on:
      - wordpress
    networks:
      - inception

volumes:
  wp-data:

networks:
    inception:
      driver: bridge