FROM alpine:3.18

RUN apk update && apk upgrade && \
	apk add --no-cache \
	mariadb mariadb-client

COPY ./tools/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

EXPOSE 3306

CMD ["entrypoint.sh"]
