# image base
FROM alpine:3.18

# install
RUN apk update && apk upgrade && \
    apk add --no-cache \
    php82-curl \
    php82 php82-fpm \
    php82-mysqli php82-json \
    wget unzip

# oficial pack from wp
RUN wget https://wordpress.org/latest.zip -P /tmp && \
    mkdir -p /var/www/wordpress && \
    unzip /tmp/latest.zip -d /tmp && \
    mv /tmp/wordpress/* /var/www/wordpress/ && \
    rm -rf /tmp/wordpress /tmp/latest.zip

# listener to nginx
RUN sed -i "s|listen = 127.0.0.1:9000|listen = 9000|g" /etc/php82/php-fpm.d/www.conf

EXPOSE 9000

# executes fmp in foreground
CMD ["/usr/sbin/php-fpm82", "-F"]