#FROM alpine:3.21.4
FROM alpine:3.18

# php82-curl

RUN apk update && apk upgrade && \
    apk add --no-cache \
    php82 php82-fpm \
    php82-mysqli php82-json \
    wget unzip

RUN wget https://wordpress.org/latest.zip \
    -P /tmp && unzip /tmp/latest.zip \
    -d /var/www/ && rm /tmp/latest.zip

RUN sed -i "s|listen = 127.0.0.1:9000|listen = 9000|g" /etc/php82/php-fpm.d/www.conf

EXPOSE 9000

CMD ["/usr/sbin/php-fpm82", "-F"]