FROM alpine:3.18

# RUN | executa comando de construção
RUN apk update && apk upgrade && \
	apk add --no-cache \
	nginx

COPY ./conf/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;"]