FROM alpine:3.18

# RUN | executa comando de construção
RUN apk update && apk upgrade && \
	apk add --no-cache \
	nginx gettext

COPY ./conf/nginx.conf /etc/nginx/nginx.template.conf
COPY ./tool/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

EXPOSE 80

CMD [ "/entrypoint.sh"]